set -e
true
true
/home/bfj994/miniconda3/envs/denovo/bin/spades-hammer /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/corrected/configs/config.info
/home/bfj994/miniconda3/envs/denovo/bin/python3 /home/bfj994/miniconda3/envs/denovo/share/spades/spades_pipeline/scripts/compress_all.py --input_file /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/corrected/corrected.yaml --ext_python_modules_home /home/bfj994/miniconda3/envs/denovo/share/spades --max_threads 16 --output_dir /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/corrected --gzip_output
true
true
/home/bfj994/miniconda3/envs/denovo/bin/spades-core /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/configs/config.info
/home/bfj994/miniconda3/envs/denovo/bin/python3 /home/bfj994/miniconda3/envs/denovo/share/spades/spades_pipeline/scripts/copy_files.py /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/before_rr.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/before_rr.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/assembly_graph_after_simplification.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/assembly_graph_after_simplification.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/final_contigs.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/contigs.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/first_pe_contigs.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/first_pe_contigs.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/strain_graph.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/strain_graph.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/scaffolds.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/scaffolds.fasta /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/scaffolds.paths /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/scaffolds.paths /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/assembly_graph_with_scaffolds.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/assembly_graph_with_scaffolds.gfa /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/assembly_graph.fastg /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/assembly_graph.fastg /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/K21/final_contigs.paths /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/contigs.paths
true
/home/bfj994/miniconda3/envs/denovo/bin/python3 /home/bfj994/miniconda3/envs/denovo/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/scaffolds.fasta --misc_dir /maps/projects/wintherpedersen/people/bfj994/keelime/sim/PB3myaHigh_fin_500_spades/misc --threshold_for_breaking_scaffolds 3
true
